---
- name: Create ad-hoc AWS EC2 Instances
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    key_name: <key-pair-name>
    instance_type: <ec2-instance-type-code>
    instance_image: <ec2-instance-image>
    instance_num: <number-of-spawned-instances>
    region: <aws-region-code>
    security_group: <custom-security-group>
    vpc: <ec2-vpc-subnet-here>
    aws_tag: <aws-instance-tags>

  tasks:
    - name: Launch specific ec2 instances
      ec2:
        key_name: "{{ key_name }}"
        group: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ instance_image }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: "{{ vpc_subnet }}"
        assign_public_ip: yes
        instance_tags:
          type: "{{ aws_tag }}"
        exact_count: "{{ instance_num }}"
        count_tag:
          type: "{{ aws_tag }}"
      register: servers

    - name: Add all new instance to host group for later use
      add_host:
        hostname: "{{ item.public_ip }}"
        groups: launched
        ansible_python_interpreter: /usr/bin/python2.7
      with_items: "{{ servers.tagged_instances }}"

    - name: Wait for SSH on all instances to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ servers.tagged_instances }}"

- name: Install python2.7
  hosts: launched
  gather_facts: False
  become: True
  tasks:
  - name: apt-get update
    raw: apt-get update -qq
  - name: Install python 2.7
    raw: apt-get install -qq python2.7

- name: Configure instance(s)
  hosts: launched
  become: True
  gather_facts: True
  vars:
  roles:
    - common
