---
- name: Install LDAP dependencies
  action: apt pkg={{item}} state=present
  with_items:
    - slapd
    - ldap-utils
    - python-ldap

- name: Start slapd
  systemd:
    name: slapd
    state: started
    enabled: yes
    masked: no
