# Common Tasks
---
  - name: Install dependencies
    apt:
      name: '{{item}}'
      state: present
    with_items:
      - iptables
      - iptables-persistent
      - fail2ban

  - name: ensure sendmail is absent
    apt:
      name: sendmail
      state: absent

  - name: setup iptables
    template:
      src: iptables-conf
      dest: '/etc/iptables/rules.v4'
      mode: '0644'
    notify:
    - load iptables from file

  - name: setup fail2ban
    template:
      src: fail2ban-conf
      dest: '/etc/fail2ban/jail.local'
      mode: '0644'
    notify:
    - restart fail2ban
